# Blockcheck

### Data Exploration
Known ponzi scheme wallets

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
df_ponzi = pd.read_csv('BTC_ponzi_dataset.csv')
df_ponzi.head(10)

,Name,Address,In Tx,Out Tx,In BTC,Out BTC,In USD,Out USD,Paying,Paid,Date 1st Tx,Date last Tx,Lifetime,Cluster Size,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Nanoindustryinv.com,1Ee9ZiZkmygAXUiyeYKRSA3tLe4vNYEAgA,1073.0,4247.0,480.177745,480.177745,"$155,352","$149,118",1034.0,488.0,8/16/14 13:21,3/6/15 21:29,202.338889,2.0,NaN,NaN,NaN,NaN
1,GrandAgoFinance,1MzNQ7HV8dQ6XQ52zBGYkCZkkWv2Pd3VG6,491.0,826.0,178.743513,178.740550,"$64,767","$64,506",489.0,233.0,9/24/14 23:53,1/29/15 13:34,126.569896,1.0,NaN,NaN,NaN,NaN
2,Cryptory,1FyedPPk923wRfmVphV1CLt3bVLGxHZXpK,10519.0,12304.0,9439.332903,9439.189818,"$4,658,008","$4,667,986",1540.0,8764.0,9/2/13 14:17,1/8/15 9:49,492.813657,232.0,NaN,NaN,NaN,NaN
3,Leancy,145SmDToAhtfcBQhNxfeM8hnS6CBeiRukY,6901.0,17805.0,3092.838344,3092.838244,"$1,896,145","$1,873,933",6833.0,1453.0,12/16/13 20:19,11/25/14 8:19,343.499873,1.0,NaN,NaN,NaN,NaN
4,Minimalism10,1FuypAdeC7mSmYBsQLbG9XV261bnfgWbgB,48.0,198.0,13.061385,13.061385,"$7,835","$7,752",47.0,64.0,2/27/14 13:21,3/27/14 8:19,27.790440,1.0,NaN,NaN,NaN,NaN
5,MiniPonziCoin,1F8ZKpjMDpnpF79mZ1pxZRoNKZgXm4Tf1d,1443.0,186.0,445.971776,445.967776,"$266,000","$263,458",301.0,287.0,2/18/14 15:05,4/14/14 18:17,55.133785,1.0,NaN,NaN,NaN,NaN
6,120cycle,1E5MCTtXn7n2svpZ1bDHZXndY9K7qQeqZP,186.0,98.0,14.282312,14.282312,"$8,264","$8,243",72.0,72.0,3/24/14 18:51,4/3/14 8:58,9.588623,78.0,NaN,NaN,NaN,NaN
7,10PERCENTBTC,1BtcBoSSnqe8mFJCUEyCNmo3EcF8Yzhpnc,7116.0,2961.0,107.715908,107.715908,"$42,894","$44,623",649.0,569.0,9/1/14 18:14,8/14/17 17:20,1077.962720,13.0,NaN,NaN,NaN,NaN
8,Ponzi.io,1ponziUjuCVdB167ZmTWH48AURW1vE64q,3438.0,2873.0,369.353632,369.333382,"$258,369","$258,281",1127.0,883.0,2/4/14 1:10,9/10/16 11:43,949.439884,33.0,NaN,NaN,NaN,NaN
9,LaxoTrade,1LaxoTrQy51LnB289VmoSAgN6J6UrJbfL9,1849.0,2949.0,1580.240959,1580.240149,"$570,106","$563,401",1028.0,30844.0,8/20/14 16:25,9/18/15 8:14,393.659167,491.0,NaN,NaN,NaN,NaN